baseURL = "https://synapseandweights.github.io/synapseandweights/"
languageCode = "en-us"
title = "Synapse & Weights"
theme = "ananke"
author = "Pradeshi Khadka"
description = "Brain scratchpad, human + AI learning"
